### ISSUE TITLE
North & East only?

### ISSUE THREAD

**Issue by tyrasd** [simon04/tyrolean-map#1]
If you want, I can contribute a couple of similarly licensed map layers and orthofotos covering the South part of Tyrol from http://geokatalog.buergernetz.bz.it/ :smiley:

**Comment by simon04** [comment]
With respect to the name of the project, this is a good idea. A few thoughts/concerns:

* Earlier or later the layer selection will overflow or contain so many elements that finding the right one is difficult. We might need to split up the entries into different groups or maybe use a hierarchical selection.
* I would like to keep the north/east to south ratio somewhat weighted, and also refrain from adding overly specific layers.
* More a thought than a worked out idea: when enabling layer X (say orthophoto CIR) we could enable corresponding layers from north/east and south Tyrol simultaneously. The differing years of the photographs might make that complicated.

So go ahead, but let's not add every single layer available in order to keep the layer list of usable length.

**Comment by tyrasd** [comment]
yeah. I've tried to keep the number of layers in #3 as low as possible (only the most important layers, merging multiple ones where applicable – e.g. the 2.5m DTM with the high-res-but-not-full-coverage sub-1m one).

> More a thought than a worked out idea: when enabling layer X (say orthophoto CIR) we could enable corresponding layers from north/east and south Tyrol simultaneously. The differing years of the photographs might make that complicated.

That would be great, but the only way to implement that would be to switch to the png image format (since jpeg doesn't have transparency) in order to display multiple matching imagery layers at the same time. But that would't be optimal regarding bandwith.
